// <auto-generated />
using System;
using DominoPontaDeQuina.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DominoPontaDeQuina.Repository.Migrations
{
    [DbContext(typeof(DominoDbContext))]
    [Migration("20260826191619_RenomeiaJogoParaPartida")]
    partial class RenomeiaJogoParaPartida
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("NomeExibicao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Jogadores", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.ParticipacaoPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("JogadorId");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("PartidaId");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Pontuacao");

                    b.Property<int>("Posicao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Posicao");

                    b.Property<bool>("Vencedor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Vencedor");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("PartidaId", "JogadorId")
                        .IsUnique();

                    b.ToTable("ParticipacoesPartida", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("FinalizadoEm");

                    b.Property<DateTime>("IniciadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("IniciadoEm");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Partidas", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("CriadoEm");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("HashSenha");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Jogador", b =>
                {
                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Jogadores")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.ParticipacaoPartida", b =>
                {
                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Jogador", "Jogador")
                        .WithMany("Participacoes")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DominoPontaDeQuina.Domain.Entities.Partida", "Partida")
                        .WithMany("Participacoes")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Jogador", b =>
                {
                    b.Navigation("Participacoes");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Partida", b =>
                {
                    b.Navigation("Participacoes");
                });

            modelBuilder.Entity("DominoPontaDeQuina.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
